using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using PSTFileFormat;

// Emits DefaultStoreTemplates.Blueprint.g.cs — the full node set of a real empty Outlook store.
// Usage: pst-genblueprint <reference-empty.pst> [outPath]
class GenBlueprint
{
    static object F(object o, string name) =>
        o.GetType().GetField(name, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)?.GetValue(o);

    static void WalkStatic(PSTFile f, BTreePage page, List<NodeBTreeEntry> acc)
    {
        if (page is NodeBTreeLeafPage leaf) { acc.AddRange(leaf.NodeEntryList); return; }
        if (page is BTreeIndexPage idx)
            foreach (var e in idx.IndexEntryList) WalkStatic(f, BTreePage.ReadFromStream(f.BaseStream, e.BREF), acc);
    }

    static void Main(string[] args)
    {
        string tpl = args.Length > 0 ? args[0] : throw new ArgumentException("Usage: pst-genblueprint <reference-empty.pst> [outPath]");
        string outPath = args.Length > 1 ? args[1] : "DefaultStoreTemplates.Blueprint.g.cs";

        var src = new PSTFile(tpl, FileAccess.Read, WriterCompatibilityMode.Outlook2007RTM);
        var nodes = new List<NodeBTreeEntry>();
        WalkStatic(src, src.NodeBTree.RootPage, nodes);
        nodes.Sort((a, b) => a.nid.Value.CompareTo(b.nid.Value));

        var header = F(src, "m_header");
        uint[] rgnid = (uint[])F(header, "rgnid");

        // Identify the 16-byte store GUID (PidTagRecordKey 0x0FF9) so the reconstructor can
        // replace it with a fresh per-store GUID. It lives in the message store node (0x21).
        var storeNode = PSTNode.GetPSTNode(src, new NodeID(0x21));
        byte[] storeGuid = storeNode.PC.GetBytesProperty(PropertyID.PidTagRecordKey);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> Full empty-store node set, reconstructed 1:1 by DefaultStoreTemplates so Outlook");
        sb.AppendLine("// accepts a from-scratch store. This generated file is now the SOURCE OF TRUTH for the empty-store");
        sb.AppendLine("// skeleton: the real Outlook-made empty PST it was originally dumped from has been retired. Do NOT");
        sb.AppendLine("// regenerate from a retired in-repo asset. See tools/pst-genblueprint/README.md for regeneration notes.");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace PSTFileFormat");
        sb.AppendLine("{");
        sb.AppendLine("    internal static partial class DefaultStoreTemplates");
        sb.AppendLine("    {");
        sb.AppendLine("        internal readonly struct BlueprintNode");
        sb.AppendLine("        {");
        sb.AppendLine("            public readonly uint Nid; public readonly uint Parent; public readonly byte[] Data;");
        sb.AppendLine("            public BlueprintNode(uint nid, uint parent, string b64) { Nid = nid; Parent = parent; Data = b64.Length == 0 ? Array.Empty<byte>() : Convert.FromBase64String(b64); }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        // The 16-byte store GUID baked into the template's node data (PidTagRecordKey + 3 folder EntryIDs).");
        sb.AppendLine($"        // The reconstructor replaces every occurrence with a fresh per-store GUID.");
        sb.Append("        internal static readonly byte[] TemplateStoreGuid = { ");
        sb.Append(string.Join(", ", Array.ConvertAll(storeGuid, b => "0x" + b.ToString("X2"))));
        sb.AppendLine(" };");
        sb.AppendLine();
        sb.Append("        internal static readonly uint[] BlueprintRgnid = { ");
        sb.Append(string.Join(", ", rgnid));
        sb.AppendLine(" };");
        sb.AppendLine();
        sb.AppendLine("        internal static BlueprintNode[] BlueprintNodes() => new BlueprintNode[]");
        sb.AppendLine("        {");
        foreach (var n in nodes)
        {
            var node = PSTNode.GetPSTNode(src, n.nid);
            byte[] data = node.DataTree?.GetData() ?? Array.Empty<byte>();
            string b64 = Convert.ToBase64String(data);
            sb.AppendLine($"            new BlueprintNode(0x{n.nid.Value:X}, 0x{n.nidParent.Value:X}, \"{b64}\"), // {n.nid.nidType} ({data.Length}B)");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"wrote {Path.GetFullPath(outPath)} : {nodes.Count} nodes, storeGuid {storeGuid.Length}B");
    }
}
